export * from './ping.controller';
export * from './piso.controller';
export * from './coordenadas.controller';
export * from './destino.controller';
export * from './fecha.controller';
export * from './reservacion.controller';
export * from './tips.controller';
export * from './usuario.controller';
export * from './imagen.controller';
